### ISSUE TITLE
Run ngrok as a service with Snap

### ISSUE THREAD

**Issue by krwenholz** [ngrok/snap-ngrok#25]
This was originally a Snapcraft forum DM.

From the individual who opened the thread, it may be a simple change. We just need to test it out.

This

```
apps: 
  ngrok:
    command: ngrok
    plugs: [network, network-bind, home, ngrok-config]
```

becomes this

```
apps:
  main:
    command: ngrok
    daemon: simple
      restart-condition: on-failure
    plugs: [network, network-bind, home, ngrok-config]
```

[Snapcraft docs for daemons](https://snapcraft.io/docs/services-and-daemons)
